---

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# INSTALLATION
- name: Add Filebeat GPG key to APT
  ansible.builtin.get_url:
      url: "{{ elastic_gpg_key_url }}"
      dest: /etc/apt/trusted.gpg.d/elastic.asc
      mode: '0644'
  when: ansible_os_family == "Debian"

- name: Add FileBeat repo to APT repositories
  ansible.builtin.apt_repository:
      repo: deb {{ elastic_packages_url }}/apt stable main
      update_cache: true
  when: ansible_os_family == "Debian"

- name: Add FileBeat repo to YUM repositories
  ansible.builtin.yum_repository:
      file: elastic
      name: elastic-7.x
      description: Elastic repository for 7.x packages
      baseurl: "{{ elastic_packages_url }}/yum"
      gpgkey: "{{ elastic_gpg_key_url }}"
      gpgcheck: true
  when: ansible_os_family == "RedHat"

- name: Install OS packages
  ansible.builtin.package:
      name: "{{ packages_to_install }}"
      state: latest
  async: 120
  poll: 10
  when: not ansible_check_mode

- name: Check installed OS packages
  ansible.builtin.package:
      name: "{{ packages_to_install }}"
      state: latest
  when: ansible_check_mode

- name: Make sure filebeat is enabled if log_collection = true
  ansible.builtin.service:
      name: filebeat
      enabled: true
      state: started
  when: log_collection

- name: Make sure filebeat is disabled if log_collection = false
  ansible.builtin.service:
      name: filebeat
      enabled: true
      state: stopped
  when: not log_collection

# CONFIGURATION (only if log_collection = true)
- name: Push logstash certificate
  ansible.builtin.copy:
      content: "{{ logstash_tls_crt }}"
      dest: "/etc/ssl/certs/logstash.crt"
      owner: root
      group: root
      mode: '0644'
  when: log_collection
  notify: Restart filebeat

- name: Push Filebeat configuration file
  ansible.builtin.template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '0600'
  when: log_collection
  notify: Restart filebeat

- name: Push Filebeat modules configuration file
  ansible.builtin.copy:
      src: "{{ item }}.yml"
      dest: /etc/filebeat/modules.d/{{ item }}.yml
      owner: root
      group: root
      mode: '0644'
  with_items:
      - iptables
      - system
  when: log_collection
  notify: Restart filebeat

- name: Push Filebeat traefik module configuration file
  ansible.builtin.template:
      src: "{{ item }}.yml.j2"
      dest: /etc/filebeat/modules.d/{{ item }}.yml
      owner: root
      group: root
      mode: '0644'
  with_items:
      - traefik
  when: inventory_hostname in groups.docker and log_collection
  notify: Restart filebeat
